config/routes.rb
Rails.application.routes.draw do
 get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#landing_page'
  get '/admin' => 'static#admin_index'
  resources :users, :images, :blog_posts, :headlines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/headline.rb
class Headline < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :screen_cap
	validates_attachment_content_type :screen_cap, content_type: /\Aimage\/.*\Z/
	validates :name, presence: true
	validates :screen_cap, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, 
	presence: true
	validates :email, 
				presence: true,
				uniqueness: true,
				format: {
					with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
				}
	def to_s
		"#{name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize  #currently only used to authorize admin accounts
  	redirect_to '/login' unless current_user && current_user.admin
  end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
	before_filter :authorize
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = BlogPost.all
	end

	def new
		@post = BlogPost.new
	end

	def edit
	end

	def create
		@post = BlogPost.create(post_params)
		if @post.save
			redirect_to blog_posts_path,
			notice: "Headline was created"
		else
			render :new
		end
	end

	def update 
		if @post.update(post_params)
			redirect_to @post, notice: 'Update successful'
		else
			render :edit
		end
	end

	def destroy
		@post = BlogPost.find(params[:id])
		@post.destroy
		redirect_to blog_posts_path
	end

	private

	def set_post
		@post = BlogPost.find(params[:id])
	end

	def post_params
		params.require(:blog_post).permit(:title, :content, :date,  :selected)
	end
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
	before_action :set_headline, only: [ :show, :edit, :update, :destroy]
	before_filter :authorize

	def index
		@headlines = Headline.all
	end

	def new
		@headline = Headline.new
	end

	def create
		@headline = Headline.create(headline_params)
		if @headline.save
			redirect_to headlines_path,
						notice: "Headline was created"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @headline.update(headline_params)
			redirect_to @headline, notice: 'Update successful'
		else
			render :edit
		end
	end

	def destroy
		@headline = Headline.find(params[:id])
		@headline.destroy
		redirect_to headlines_path
	end

	# def select
	# 	@unselect = Headline.all
	# 	@unselect.each do |headline|
	# 		headline.selected = false
	# 		headline.save
	# 	end
	# 	@headline.selected = true
	# 	@headline.save
	# 	render :index
	# end

	private

	def set_headline
		@headline = Headline.find(params[:id])
	end

	def headline_params
		params.require(:headline).permit(:text, :selected)
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: [:show, :update, :edit, :destroy]
	before_filter :authorize
	
	def index
		@images = Image.all
	end

	def new
		@image = Image.new
	end

	def create
		@image = Image.new(image_params)
		
		if @image.save
			redirect_to @image, notice: "Image saved"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @image.update(image_params)
			redirect_to @image, notice: 'Update successful'
		else
			render :edit
		end
	end

	def destroy
		@image = Image.find(params[:id])
		@image.destroy
		redirect_to images_path
	end

	private

	def image_params
		params.require(:image).permit(:name, :screen_cap, :selected)
	end
	
	def set_image
		@image = Image.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if user.admin
        redirect_to '/admin'
      else
        redirect_to '/'
      end
    else
      redirect_to '/login'
    end
  end
  def destroy
  	session[:user_id] = nil
  	redirect_to '/login'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	before_filter :authorize, only: [:admin_index]
	def admin_index
	end
	def landing_page
		@selected_headline = Headline.where(selected: true).first || Headline.new(text: "Your title here")
		@selected_image = Image.where(selected: true).first

		@blog_posts = BlogPost.where(selected: true)
		@post_one = @blog_posts.first || BlogPost.new(title: 'example post', date: 'Jan/1/2020')
		@post_two = @blog_posts[1] || BlogPost.new(title: 'example post', date: 'Jan/2/2020')
		@post_three = @blog_posts[2] || BlogPost.new(title: 'example post', date: 'Jan/3/2020')

		@images = Image.where(selected: true)
		if @images.first
			@selected_image = @images.first.screen_cap
		else
			@selected_image = "http://www.davidlai.me/wp-content/uploads/2011/09/6a01310fb8e76f970c01310fbda40f970c.png"
		end 
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :update, :destroy, :edit]
	before_filter :authorize, except: [:new, :create]

	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.create(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, 
			notice: "#{@user.name}, your account was successfully created."
		else
			render :new
		end
	end
	def edit
	end
	def update
		if @user.update(user_params)
			redirect_to @user, notice: 'Update successful'
		else
			render :edit
		end
	end
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private
	def set_user
		@user = User.find(params[:id])
	end
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/_form.html.erb
_form.html.erb
<%= form_for @post do |form| %>
<div class="field">
	<p><%= form.label :title %></p>
	<p><%= form.text_field :title %></p>
</div>
<div class="field">
	<p><%= form.label :content %></p>
	<p><%= form.text_area :content %></p>
</div>
<div class="field">
	<p><%= form.label :date %></p>
	<p><%= form.date_field :date %></p>
</div>
<div class="field">
	<%= form.label :selected %>
	<%= form.check_box :selected %>
</div>
<div>
	<p><%= form.submit %></p>
</div>
<% end %>

app/views/blog_posts/edit.html.erb
edit.html.erb
<p><%= link_to 'Back', blog_posts_path %></p>
<%= render 'form' %>

app/views/blog_posts/index.html.erb
index.html.erb

<h4><%= link_to 'Admin Index', '/admin' %></h4>
<p><%= link_to 'Create Post', new_blog_post_path %></p>
<p><% @posts.each do |post| %></p>
<p><%= post.title %></p>
<p><%= post.date %></p>
<p><%= post.selected? %></p>
<%= link_to 'show', post %>
<% end %>

<p><%= link_to 'Home Page', root_path %></p>

app/views/blog_posts/new.html.erb
new.html.erb
<p><%= link_to 'Back', blog_posts_path %></p>
<%= render 'form' %>

app/views/blog_posts/show.html.erb
show.html.erb
<%= link_to 'Back', blog_posts_path %>
<ul>
	<li><%= @post.title %></li>
	<li><%= @post.content %></li>
	<li><%= @post.date %></li>
	<li><%= @post.selected? %></li>
	<li><%= link_to 'Edit', edit_blog_post_path(@post) %></li>
</ul>

app/views/headlines/_form.html.erb
_form.html.erb
<%= form_for @headline do |form| %>
<div class="field">
	<%= form.label :text %>
	<%= form.text_field :text %>
</div>
<div class="field">
	<%= form.label :selected %>
	<%= form.check_box :selected %>
</div>
<div>
	<%= form.submit %>
</div>
<% end %>

app/views/headlines/edit.html.erb
edit.html.erb


<%= render 'form', headline: @headline %>

<%= link_to 'Back', headlines_path %>

app/views/headlines/index.html.erb
index.html.erb
<p><%= link_to 'Admin Index', '/admin' %></p>
<p><%= link_to 'Create a headline', new_headline_path %></p>
<% @headlines.each do |headline| %>
<p><%= "-" * 50 %></p>
<p><%= headline.text %></p>
<p><%= headline.created_at %></p>
<p>selected:
<%= link_to "#{headline.selected?}", edit_headline_path(headline) %>
</p>
<p><%= link_to 'Show', headline %></p>
<p><%= link_to 'Edit', edit_headline_path(headline) %></p>
<p><%= link_to 'Destroy', headline, method: :delete, data: {confirm: 'Delete for realz?'} %></p>
<p><%= "-" * 50 %></p>

<% end %>
<p><%= link_to 'Home Page', root_path %></p>

<%#= button_to headline ,'headlines#select' %>

app/views/headlines/new.html.erb
new.html.erb

<%= form_for @headline do |form| %>
<div class="field">
	<%= form.label :text %>
	<%= form.text_field :text %>
<div>
	<%= form.submit %>
</div>
<% end %>

app/views/headlines/show.html.erb
show.html.erb
<p><%= notice %></p>
<p><%= link_to 'Back', headlines_path %></p>

<p><%= @headline.text %></p>
<p>Selected:<%= @headline.selected? %></p>
<p><%=	link_to 'Edit', edit_headline_path(@headline) %></p>
<p> <%= link_to 'Destroy', @headline, method: :delete, data: {confirm: 'Delete for realz?'} %></p>

app/views/images/_form.html.erb
<%= form_for @image do |form| %>
<div class="field">
	<%= form.label :name %>
	<%= form.text_field :name %>
</div>
<div class="field">
	<%= form.label :screen_cap %>
	<%= form.file_field :screen_cap %>
</div>
<div class="field">
	<%= form.label :selected %>
	<%= form.check_box :selected %>
</div>
<div>
	<%= form.submit %>
</div>
<% end %>

app/views/images/edit.html.erb
edit.html.erb

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
index.html.erb
<p><%= link_to 'Home Page', root_path %></p>

<p><%= link_to 'Admin Index', '/admin' %></p>
<p><%= link_to 'Create new image', new_image_path %></p>

<% @images.each do |image| %>
<ul>
	<li><%= image.name %></li>
	<li>Selected: <%= image.selected? %></li>
	<li><%= link_to 'Show', image %></li>
	<li><%= link_to 'Edit', edit_image_path(image) %></li>
	<li><%= link_to 'Destroy', image, method: :delete, data: {confirm: 'Delete for realz?'} %></li>
	<!-- <li><%#= image_tag image.screen_cap.url %></li> -->
</ul>
<%end%>
<p><%= link_to 'Home Page', root_path %></p>

app/views/images/new.html.erb
<%= link_to 'Back', images_path %>
<%= render 'form', image: @screen_cap %>

app/views/images/show.html.erb
show.html.erb
<p><%= notice %></p>
<p><%= link_to 'Back', images_path %></p>

<p><%= @image.name %></p>
<p>Selected: <%= @image.selected? %></p>
<p><%= image_tag @image.screen_cap.url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimbeProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
_form.html.erb

<%= form_for @user do |form| %>
<div class="field">
	<p><%= form.label :name %></p>
	<p><%= form.text_field :name %></p>
</div>
<div class="field">
	<p><%= form.label :email %></p>
	<p><%= form.text_field :email %></p>
</div>
<div class="field">
	<p><%= form.label :password %></p>
	<p><%= form.password_field :password %></p>
</div><div class="field">
	<p><%= form.label :password_confirmation %></p>
	<p><%= form.password_field :password_confirmation %></p>
</div>
<div>
	<p><%= form.submit %></p>
</div>
<% end %>

app/views/users/edit.html.erb
edit.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p><%= link_to 'Home Page', root_path %></p>

<%= link_to 'Admin Index', '/admin' %>
<%= link_to 'Create User', new_user_path %>
<% @users.each do |user| %>
<ul>
	<li><%= user.name %></li>
	<li><%= user.email %></li>
	<li>Admin: <%= user.admin? %></li>
	<li><%= link_to 'Show', user %></li>
</ul>
<% end %>
<p><%= link_to 'Home Page', root_path %></p>

app/views/users/new.html.erb
<%= link_to 'Back', users_path %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= link_to 'Back', users_path %>
<ul>
	<li><%= @user.name %></li>
	<li><%= @user.email %></li>
	<li>Admin: <%= !@user.admin.nil? %></li>
	<li><%= link_to 'Edit', edit_user_path(@user) %></li>
</ul>